---
# Inventaire Ansible — MSPR NordTransit Lab
# Changer ansible_host selon le Proxmox cible (pve02 perso ou ecole)

all:
  children:
    proxmox:
      hosts:
        pve02:
          ansible_host: "192.168.2.4"
          ansible_user: root
          ansible_connection: ssh

        # Decommenter pour utiliser le Proxmox de l'ecole :
        # pve-ecole:
        #   ansible_host: "10.x.x.x"      # IP du Proxmox ecole
        #   ansible_user: root
        #   ansible_connection: ssh

    # -------------------------------------------------------
    # Hosts du lab (accessibles apres creation des VMs)
    # -------------------------------------------------------

    lab_firewalls:
      hosts:
        fw_siege:
          ansible_host: 172.16.132.1
          ansible_user: admin
          ansible_password: "{{ vault_pfsense_password }}"
          ansible_connection: ssh
          ansible_shell_type: csh
        fw_azure:
          ansible_host: 10.100.0.1
          ansible_user: admin
          ansible_password: "{{ vault_pfsense_password }}"
          ansible_connection: ssh
          ansible_shell_type: csh

    lab_windows:
      hosts:
        dc01:
          ansible_host: 172.16.132.10
          ansible_user: Administrator
          ansible_password: "{{ vault_windows_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
        dc02:
          ansible_host: 172.16.132.11
          ansible_user: Administrator
          ansible_password: "{{ vault_windows_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
        dc_azure:
          ansible_host: 10.100.0.10
          ansible_user: Administrator
          ansible_password: "{{ vault_windows_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore

    lab_linux:
      hosts:
        wms:
          ansible_host: 172.16.132.20
          ansible_user: wmsadmin
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_connection: ssh

    lab_voip:
      hosts:
        ipbx:
          ansible_host: 172.16.132.30
          ansible_user: root
          ansible_password: "{{ vault_freepbx_password }}"
          ansible_connection: ssh
